### ISSUE TITLE
Stack corruption in Squeak 4.5 in a Primitive

### ISSUE THREAD

**Issue by abstraktor** [abstraktor/SqueakJS#15]
Steps to reproduce:
1. Open [Squeak4.5-13680](http://localhost:9090/run/index.html#url=http://freudenbergs.de/bert/squeakjs&files=[Squeak4.5-13680.image,Squeak4.5-13680.changes,SqueakV41.sources)
2. Click on the very top right Fullscreen-Button
3. I see an alert "receivers don't match"

In [berts current version](http://bertfreudenberg.github.io/SqueakJS/run/#url=http://freudenbergs.de/bert/squeakjs&files=[Squeak4.5-13680.image,Squeak4.5-13680.changes,SqueakV41.sources]), it works.

**Comment by Nilos** [comment]
I thought we fixed this ....

**Comment by codefrau** [comment]
You still have `entry.argCount || argCount` in send() which is wrong and causing corruption.

**Comment by abstraktor** [comment]
Actually the problem is not the number of arguments copied at this point, but the stack pointer is shifted by one (which of course could be the result of a wrong argCount in a previous send).

**Comment by abstraktor** [comment]
I think it relates to a missing Breakout after the primitive is run. Fullscreen freezes the image, but our primitives are not followed by the Breakout-check. So the upcoming code is run before the image is unfrozen. This explains why the error persists when turning of peepholing and inline caching.

Maybe the stack is just missing the return value of that primitive (although I didn't find that point yet).

I'll probably go on looking at it on  Tuesday

**Comment by Nilos** [comment]
This one is not caused by any argCount or stack problem, but simply by a succesfull primitive not returning true.

**Comment by Nilos** [comment]
Fixed in 896a535

**Comment by abstraktor** [comment]
confirmed. you are my hero.
